---
title: "F24_build"
output: html_document
date: "2024-12-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages (now: many unnecessary)
```{r, include = F}
gc()
library(data.table) #for data loading
library(readxl) #for reading in FRED data
library(tidyverse) #for data work
install.packages("janitor")
library(janitor) #for clean_names
install.packages("srvyr")
library(srvyr) #for weighting

install.packages("fastDummies")
library(fastDummies) #for dummies- maybe

install.packages("fixest")
library(fixest) #for regression - maybe
library(haven) #for stata data export/import

install.packages("stargazer")
library(stargazer) #for latex output

library(broom) #convert fixest outputs to data frames
```

Download raw file
```{r, include = F}
gc()
#mac
# F24_pull1 <- fread("/Users/njrich/Downloads/F24_pull1.csv") %>%
#   clean_names()
#windows
F24_pull1 <- fread("C:\\Users\\njrich\\Downloads\\F24_pull1.csv") %>%
  clean_names()

#download cleaned-ish data
#mac
# cleanish <- read_dta("/Users/njrich/Downloads/clean_dataframe.dta")
#windows

```

Make working_df dataframe to preserve original pull
```{r, include = F}
gc()
working_df <- F24_pull1

```

Data labeling and some variable creation - add var for have kids?
```{r, include = F}
gc()
#label states using chunking for memory management
add_context <- function(df_samesex) {
gc()

#general function to add in state-based labels (for both ex-ante and ex-post states)
state_labels <- function(df, variable, label) {

df <- df %>%
  mutate(state = as.character(variable))

df <- df %>%
  mutate(state = case_when(
    state == "1" ~ "AL",
    state == "2" ~ "AK",
    state == "4" ~ "AZ",
    state == "5" ~ "AR",
    state == "6" ~ "CA",
    state == "8" ~ "CO",
    state == "9" ~ "CT",
    state == "10" ~ "DE",
    TRUE ~ state))

gc()
df <- df %>%
  mutate(state = case_when(
    state == "11" ~ "DC",
    state == "12" ~ "FL",
    state == "13" ~ "GA",
    state == "15" ~ "HI",
    state == "16" ~ "ID",
    state == "17" ~ "IL",
    state == "18" ~ "IN",
    state == "19" ~ "IA",
    state == "20" ~ "KS",
    TRUE ~ state))

gc()
df <- df %>%
  mutate(state = case_when(
    state == "21" ~ "KY",
    state == "22" ~ "LA",
    state == "23" ~ "MI",
    state == "24" ~ "MD",
    state == "25" ~ "MA",
    state == "26" ~ "ME",
    state == "27" ~ "MN",
    state == "28" ~ "MS",
    state == "29" ~ "MO",
    state == "30" ~ "MT",
    TRUE ~ state))

gc()
df <- df %>%
  mutate(state = case_when(
    state == "31" ~ "NE",
    state == "32" ~ "NV",
    state == "33" ~ "NH",
    state == "34" ~ "NJ",
    state == "35" ~ "NM",
    state == "36" ~ "NY",
    state == "37" ~ "NC",
    state == "38" ~ "ND",
    state == "39" ~ "OH",
    state == "40" ~ "OK",
    TRUE ~ state))

gc()
df <- df %>%
  mutate(state = case_when(
    state == "41" ~ "OR",
    state == "42" ~ "PA",
    state == "44" ~ "RI",
    state == "45" ~ "SC",
    state == "46" ~ "SD",
    state == "47" ~ "TN",
    state == "48" ~ "TX",
    state == "49" ~ "UT",
    state == "50" ~ "VT",
    state == "51" ~ "VA",
    state == "53" ~ "WA",
    state == "54" ~ "WV",
    state == "55" ~ "WI",
    state == "56" ~ "WY",
    state == "72" ~ "PR",
    state == "97" ~ "OMI", #Overseas Military Installations
    state == "99" ~ NA,
    TRUE ~ state
  ))



#label legalization date from Gerstmann "2012" pqper
gc()
df <- df %>%
  mutate(date_legalization = state)

df <- df %>%
  mutate(date_legalization = case_when (
    date_legalization == "AL" ~ "2015",
    date_legalization == "AK" ~ "2014",
    date_legalization == "AZ" ~ "2014",
    date_legalization == "AR" ~ "2015",
    date_legalization == "CA" ~ "2013", #watch legalized/repealed timeline
    date_legalization == "CO" ~ "2014",
    date_legalization == "CT" ~ "2008",
    date_legalization == "DE" ~ "2013",
    date_legalization == "DC" ~ "2009",
    date_legalization == "FL" ~ "2015",
    TRUE ~ date_legalization))

gc()
df <- df %>%
  mutate(date_legalization = case_when(
    date_legalization == "GA" ~ "2015",
    date_legalization == "HI" ~ "2013",
    date_legalization == "ID" ~ "2014",
    date_legalization == "IL" ~ "2013",
    date_legalization == "IN" ~ "2014",
    date_legalization == "IA" ~ "2009",
    date_legalization == "KS" ~ "2014",
    date_legalization == "KY" ~ "2015",
    date_legalization == "LA" ~ "2015",
    date_legalization == "ME" ~ "2012",
    TRUE ~ date_legalization))

gc()
df <- df %>%
  mutate(date_legalization = case_when(
    date_legalization == "MD" ~ "2012",
    date_legalization == "MA" ~ "2003",
    date_legalization == "MI" ~ "2015",
    date_legalization == "MN" ~ "2013",
    date_legalization == "MS" ~ "2015",
    date_legalization == "MO" ~ "2015",
    date_legalization == "MT" ~ "2014",
    date_legalization == "NE" ~ "2015",
    date_legalization == "NV" ~ "2014",
    date_legalization == "NH" ~ "2009",
    TRUE ~ date_legalization))

gc()
df <- df %>%
  mutate(date_legalization = case_when(
    date_legalization == "NJ" ~ "2013",
    date_legalization == "NM" ~ "2013",
    date_legalization == "NY" ~ "2011",
    date_legalization == "NC" ~ "2014",
    date_legalization == "ND" ~ "2015",
    date_legalization == "OH" ~ "2015",
    date_legalization == "OK" ~ "2014",
    date_legalization == "OR" ~ "2014",
    date_legalization == "PA" ~ "2014",
    date_legalization == "RI" ~ "2013",
    TRUE ~ date_legalization))

gc()
df <- df %>%
  mutate(date_legalization = case_when(
    date_legalization == "SC" ~ "2014",
    date_legalization == "SD" ~ "2015",
    date_legalization == "TN" ~ "2015",
    date_legalization == "TX" ~ "2015",
    date_legalization == "UT" ~ "2014",
    date_legalization == "VT" ~ "2009",
    date_legalization == "VA" ~ "2014",
    date_legalization == "WA" ~ "2012",
    date_legalization == "WV" ~ "2014",
    date_legalization == "WI" ~ "2014",
    date_legalization == "WY" ~ "2014",
    date_legalization == "PR" ~ "2015",
    date_legalization == "OMI" ~ "2015",
    TRUE ~ date_legalization
  ))

gc()
df <- df %>%
  mutate(date_legalization = as.numeric(date_legalization))

gc()
df <- df %>%
  mutate(legal_state = ifelse(year >= date_legalization, 1, 0)) %>% #watch greater than/greater than or equal to
  mutate(old_legal = ifelse(year < 2015, legal_state, if_else(date_legalization == 2015, 0, 1)))  %>% #track states as of 2014 not legal still even if become legal later- note dynamic before 2014 as states become legal, CHECK LOGIC

return(df)
}

#differentiate whether descriptive state characteristics are for the ex-ante or ex-post state
add_exantepost <- function(df, variable, label) {

  if(label == "expost") {
  df <- df %>%
    rename(statefip = variable, expost_state = state, expost_date_legalization = date_legalization, expost_legal_state = legal_state, expost_old_legal = old_legal)
 }  else {
  df <- df %>%
    rename(paststate = variable, exante_state = state, exante_date_legalization = date_legalization, exante_legal_state = legal_state, exante_old_legal = old_legal)
}
  return(df)
}

#bring above 2 functions together- have to be broken up for memory constraints
add_state_labels <- function(df, variable, label) {
  df <- df %>%
  rename(variable = {{ variable }})
  df <- state_labels(df, variable, label)
  df <- add_exantepost(df, variable, label)
  gc()
  return(df)
}


#prelim filtering for ease of use
df_samesex <- df_samesex %>%
  filter(statefip < 60) %>%
  filter(migplac1 < 60) %>%
  mutate(past_state = ifelse(migplac1 == 0, statefip, migplac1)) #for ease of coding above and below bc subtle differences and similarities between statefip1 and migplac1

#ex-post (ie look at legal status of state moved to)
df_samesex <- add_state_labels(df_samesex, statefip, "expost")

#ex-ante (ie look at legal status of state moved from)
df_samesex <- add_state_labels(df_samesex, past_state, "exante") #likely more efficient way...

#add person labels 
df_samesex <-df_samesex %>%
  mutate(migrant = ifelse(migplac1 == 0, 0, 1)) %>% #watch techdef here
  mutate(sex_sp = ifelse(sex_sp == 9, NA, sex_sp)) %>% #this is also inputted later, for sanity add this here too (make more efficient later)
  mutate(in_samesex = ifelse(sex_sp == sex, 1, 0)) %>% #watch techdef here/coding issues
  mutate(in_oppositesex = ifelse((sex_sp != sex) & !is.na(sex_sp), 1, 0)) %>% #watch techdef here
  mutate(post_2015 = ifelse(year >= 2015, 1, 0))
return(df_samesex)

#collapse for readability/organization above?
}
#summary_stats <- add_context(summary_stats)
working_df <- add_context(working_df)

#oop watch expost v exante labeling (destination v origin state difference)
```

Data cleaning (mostly technical and resolving missing occurrences)
```{r, include = F}
gc()
technical_cleaning <- function (data) {
  gc()
  
  data <- data %>%
    mutate(expost_state = factor(expost_state)) %>%
    mutate(exante_state = factor(exante_state)) %>%
    filter(sex != 9) %>%
    filter(age != 999) %>%
    mutate(race = factor(race))
  gc()
  data <- data %>%
    filter(educ != 99) %>%
    mutate(educ = factor(educ)) %>%
    filter(empstat != 9) %>%
    mutate(empstat = factor(empstat)) %>%
    mutate(occ = factor(occ)) %>%
    mutate(ind = factor (ind)) %>%
    filter(inctot != 9999998)
  gc()
  data <- data %>%
    mutate(inctot = ifelse(inctot == 9999999, NA, inctot)) %>%
    filter(migplac1 <= 57) %>%
    mutate(migplac1 = factor(migplac1)) %>% #ensure migrants have state identified
    filter(qsex != 4) %>% #get rid of those with imputed sex- watch partner's sex here too
    filter(qrace != 3) %>% #get rid of missing race
    mutate(offpov = factor(offpov)) %>%
    mutate(sex_sp = ifelse(sex_sp == 9, NA, sex_sp)) %>% #relabel no have partner, watch placement in code
    filter(!is.na(sex_sp)) %>% #to restrict to only those in relationships (argue more model cleaning than technical cleaning oops)
    mutate(sex_sp = factor(sex_sp))
  gc()
  data <- data %>%
    filter(bpl <= 57) #exclude people born outside of the US/in US territories
  return(data)
}

working_df <- technical_cleaning(working_df)

#oop works just very slow
```

Export build
```{r, include = F}
gc()
selected_data <- working_df %>%
  select(migrant, in_samesex, expost_old_legal, exante_old_legal, post_2015, sex, age, race, educ, occ, ind, bpl, inctot, perwt, year, expost_state, exante_state)
rm(F24_pull1, summary_stats, add_context, technical_cleaning)

#Export for STATA analysis (can use other purposes low key too)
write_dta(selected_data, "C:\\Users\\njrich\\Downloads\\clean_dataframe.dta")

gc()

```

R regression (outdated)
```{r, include = F}
gc()
#desired (ish) model - still missing stuff- too big for computer (61gb):
# full_model <- feols(migrant ~ in_samesex * expost_old_legal * post_2015 + i(sex) + age + i(race) + i(educ) + i(occ) + i(ind) + i(bpl) + inctot | year + expost_state, weights = perwt, data = selected_data)
# summary(full_model)

#what computer can handle
# model <- feols(migrant ~ in_samesex * expost_old_legal * post_2015 + i(sex), weights = ~perwt, data = selected_data) #rip cluster, SE, how incl in_samesex, oh my goodness regression way too big, think through fixed effects and clustering where put relative to regression
# summary(model)

#mac test
# model <- feols(migrant ~ in_samesex * expost_old_legal * post_2015 + i(sex), weights = ~perwt, data = cleanish) #stil need to cluster
# base_model <- tidy(model)
# base_model
#watch missing values (like a lot of them need to go back and work thorugh stuff)
#watch run tests to see what parallel trends assumptions holds for/does not hold for
#watch time frame issues
#watch clustering- might need to add more variables to cleanish- maybe by source state/household?
```



Test r regression (outdated)
```{r, include = F}
# gc()
# set.seed(123)
# data_sample <- slice_sample(selected_data, n = 10000)
# sample_model <- model <- feols(migrant ~ in_samesex * expost_old_legal * post_2015 + i(sex) + age + i(race) + i(educ) + i(occ) + i(ind) + i(bpl) + inctot, weights = ~perwt, data = data_sample) #watch still remaining issues, oop removing fixed effects
# summary(sample_model)
#watch missing values
#yay collinearity solving my problems ish oop still need solve clustering- hmm how much more to mess with, think what is equivalent treatment ie legalization effect vs post 2015 convergence stuff
#hmmm... need set expost_old_legal va and post_2015 variable as different than time and year fixed effects... hurt my heart... estimate seem rather high need more here to fully flesh out the model

#12/15/24 comments
#uh oh 1 positive 1 negative, need to keep iterating but suggests maybe just 1 small effect
#watch coding issues with multiple re-runnings
#REALLY DO NEED TO THINK IF NEED SEPARATE STATE/YEAR FIXED EFFECTS (do not believe need to use i() function)
```

Export R regression (outdated)
```{r, include = F}
# gc()
# write.csv(base_model, file = "/Users/njrich/Desktop/same-sex-migration/outputs/base_model.csv")

#keep things cleaner:)
```
