---
title: "data_cleaning"
output: html_document
date: "2024-03-07"
---
Load packages
```{r}
gc()
library(tidyverse)
#install.packages("arrow")
source("https://raw.githubusercontent.com/apache/arrow/master/r/R/install-arrow.R")
install_arrow(minimal = Sys.getenv("LIBARROW_MINIMAL", FALSE)) #to turn off minimal... see if need this long term
library(arrow)

```

Download the data (hmm maybe just use computer with more RAM)
```{r}
pull1_csv <- open_dataset(
  sources = "/Users/njrich/Desktop/Econ495/same-sex-migration/Data/pull1/pull1.csv",
  col_types = schema(CBSERIAL = int64(), COUPLETYPE = int64(), SSMC = int64(), 
                     MIGPLAC1 = int64(), MIGCOUNTY1 = int64(), SPMPOV = int64(),
                     OFFPOV = int64()),
                     format = "csv") 
```

Identify individuals in same-sex relationships
```{r}
gc()
partner <- pull1_csv %>%
  select(YEAR, SERIAL, PERNUM, SEX) %>% #rename sex var for clarity?
  compute()

#will expand variables over time  (tentative use FIP)
df_partners <- pull1_csv %>%
  left_join(partner, join_by(YEAR, SERIAL, SPLOC == PERNUM), suffix = c(".indv", ".partner")) %>% #WATCH CLARITY WHERE SPLOC IS
  collect()

df_samesex <- df_partners %>% #WATCH CLARITY WHERE SPLOC IS
  mutate(in_samesex = case_when(
    (SEX.indv == 1) & (SEX.partner == 1) ~ 1, #gay
    (SEX.indv == 2) & (SEX.partner == 2) ~ 1, #gay
    (SEX.indv == 2) & (SEX.partner == 1) ~ 0, #straight
    (SEX.indv == 1) & (SEX.partner == 2) ~ 0, #straight
    (SEX.indv == 2) & (SEX.partner == 1) ~ 9 #NA
  ))

rm(partner, df_partners)
#convert back to arrow?, sigh weights              
```

Label states+
```{r}

```