---
title: "F24_build"
output: html_document
date: "2024-12-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages (now many unnecessary)
```{r, include = F}
gc()
library(data.table) #for data loading
library(readxl) #for reading in FRED data
library(tidyverse) #for data work
install.packages("janitor")
library(janitor) #for clean_names
install.packages("srvyr")
library(srvyr) #for weighting

install.packages("fastDummies")
library(fastDummies) #for dummies- maybe

install.packages("fixest")
library(fixest) #for regression - maybe
library(haven) #for stata data export/import

install.packages("stargazer")
library(stargazer) #for latex output

library(broom) #convert fixest outputs to data frames
```

Download clean data
```{r, include = F}
gc()

clean_df <- read_dta("C:\\Users\\njrich\\Downloads\\clean_dataframe.dta") %>%
  clean_names()

```

Make survey object
```{r, include = F}
gc()

summary_stats <- as_survey(clean_df, weights = perwt) #note: exclude rep_wts so standard errors are inaccurate (file otherwise insanely big- talk someone about it)

```

Make summary stats (will need to do a lot of work to functionalize)
```{r, include = F}
gc()
#count those in/not in same sex
count_same_sex <- summary_stats %>%
  group_by(year) %>%
  summarize(prop_samesex = survey_mean(in_samesex, na.rm = T)) %>%
  select(-prop_samesex_se) #THIS IS NOT AS ACCURATE WITHOUT REPWEIGHTS- DO NOT HAVE- numbers look so much better already:)

gc()
#count those in/not in opposite sex
count_same_sex <- summary_stats %>%
  group_by(year) %>%
  summarize(prop_oppositesex = survey_mean(in_oppositesex, na.rm = T)) %>%
  select(-prop_oppositesex_se) #THIS IS NOT AS ACCURATE WITHOUT REPWEIGHTS- DO NOT HAVE- numbers look so much better already:)


#NOTE: ABOVE THIS STEP, I FILTER OUT ALL OF THOSE NOTE IN RELATIONSHIPS, MAKING ABOVE MORE USELESS BAR EDITING

gc()
#count male/female
count_male_female <- summary_stats %>%
  group_by(year) %>%
  mutate(sex = ifelse(sex == 9, NA, sex - 1)) %>%
  summarize(prop_fem = survey_mean(sex, na.rm = T)) %>%
  select(-prop_fem_se) #THIS IS NOT AS ACCURATE WITHOUT REPWEIGHTS- DO NOT HAVE- numbers look so much better already:)

gc()
#count prop in legal same-sex state/not:
count_in_legal <- summary_stats %>%
  group_by(year) %>%
  summarize(prop_in_legal = survey_mean(expost_legal_state, na.rm = T)) %>%
  select(-prop_in_legal_se) #THIS IS NOT ACCURATE WITHOUT REPWEIGHTS- DO NOT HAVE- numbers look so much better already:)

gc()
#analyze by what triple diff will ultimately look like
reg_graph_data <- summary_stats %>%
  filter((in_samesex == 1) | (in_samesex == 0)) %>% #WATCH ADJUSTMENTS HERE FOR BETTER COMPARISON
  mutate(mig_type = ifelse((migrant == 1) & (expost_old_legal == 1), "to_expost_old_legal", ifelse((migrant == 1) & (expost_old_legal == 0), "to_old_not_legal", "not a migrant"))) %>% #PUT THIS VARIABLE IN FUNCTION ABOVE OI STATA SET UP (issues, watch dynamism, OI LOGIC CHECK)
  mutate(to_expost_old_legal = ifelse(mig_type == "to_expost_old_legal", 1, 0)) %>% #use pivot wider?
  mutate(to_old_not_legal = ifelse(mig_type == "to_old_not_legal", 1, 0)) %>% #use pivot wider?
  group_by(year, in_samesex) %>%
  summarize(prop_to_expost_old_legal = survey_mean(to_expost_old_legal, na.rm = T),
            prop_to_old_not_legal = survey_mean(to_old_not_legal, na.rm = T)) %>%
  ungroup()%>%
  select(-prop_to_expost_old_legal_se, -prop_to_old_not_legal_se) #YAY SO COOL OK THINK GRAPHS

#FUNCTIONALIZE BELOW CODE
gc()
same_sex_trends <- reg_graph_data %>%
  filter(in_samesex == 1) %>%
  pivot_longer(cols = c(prop_to_expost_old_legal, prop_to_old_not_legal), names_to = "destination_state") %>%
  ggplot(aes(x = year)) +
    geom_line(aes(y = value, color = destination_state)) +
    scale_x_binned() +
    labs(title = "Migration of Same-Sex Individuals to Various States",
         x = "Year",
         y = "Fraction to State Type",
         color = "Destination State") #watch clarifications needed here
same_sex_trends

opposite_sex_trends <- reg_graph_data %>%
  filter(in_samesex == 0) %>% #THIS NEEDS ADJUSTMENT
  ggplot(aes(x = year)) +
    geom_line(aes(y = prop_to_expost_old_legal), color = "blue") +
    geom_line(aes(y = prop_to_old_not_legal), color = "red") #oop add labels etc etc
opposite_sex_trends

subtracted_trends <- reg_graph_data %>%
  mutate(in_samesex = ifelse(in_samesex == 1, "samesex", "not_samesex")) %>% #THIS NEEDS ADJUSTMENT FOR RELATIVE COMPARISON BETTER
  pivot_wider(names_from = in_samesex, values_from = c(prop_to_expost_old_legal, prop_to_old_not_legal)) %>%
  mutate(diff_expost_old_legal = prop_to_expost_old_legal_samesex - prop_to_expost_old_legal_not_samesex,
        diff_old_not_legal = prop_to_old_not_legal_samesex - prop_to_old_not_legal_not_samesex ) %>% #oi naming, put some of these in data columns then functionalize
  ggplot(aes(x = year)) +
    geom_line(aes(y = diff_expost_old_legal), color = "blue") +
    geom_line(aes(y = diff_old_not_legal), color = "red")
subtracted_trends #subtract from same-sex

#hmm watch trends and issues with old legal definitions
#make graphs prettier
#oopsy functionalize, watch plots + weights
#WATCH SELECTING AND FILTERING
#interesting
#go past 2019? hmm hmm hmm, compare migration rates overall?
#oi so much more cleaning work left to do need to be systematic
#watch tech fixes, esp. for opposite sex couples (add indicator function to big cleaning function a few steps up)
#so much more to adjust and prettify and functionalize here but good spot (oi vey labels)
#also need smaller random sampled data for break for testing stuff (not final regression)
#oop standard errors
#need make output var, need think more on stata too interaction terms make sure actually have everything
```


Export charts
```{r, include = F}
gc()
#code
```

```